BABYLON;
BABYLON.Vector3;
BABYLON.VRCameraMetrics;
BABYLON.VRCameraMetrics.GetDefault = function() {};
BABYLON.VRDeviceOrientationFreeCamera;
BABYLON.Mesh;
BABYLON.Mesh.CreatePlane = function() {};
BABYLON.Mesh.BILLBOARDMODE_ALL;
BABYLON.StandardMaterial;
BABYLON.Color3;
BABYLON.Texture;
BABYLON.Vector2
BABYLON.Engine;
BABYLON.SceneLoader;
BABYLON.SceneLoader.Load = function() {};
BABYLON.Sound;
BABYLON.Scene;
BABYLON.Scene.FOGMODE_EXP2;
BABYLON.Scene.FOGMODE_LINEAR;
BABYLON.SceneOptimization;
BABYLON.LensRenderingPipeline;
BABYLON.Engine.ALPHA_ADD;
BABYLON.Engine.ALPHA_COMBINE;
BABYLON.Vector3.Project = function() {};
BABYLON.Matrix;
BABYLON.Matrix.Identity = function() {};
BABYLON.ScreenSpaceCanvas2D;
BABYLON.Size;
BABYLON.Canvas2D;
BABYLON.Canvas2D.CACHESTRATEGY_CANVAS;
BABYLON.Text2D;
BABYLON.Frustum;
BABYLON.Frustum.GetPlanes = function() {};
BABYLON.Ray;
BABYLON.CubeTexture;
BABYLON.Texture.SKYBOX_MODE;
BABYLON.SceneOptimizer.OptimizeAsync = function() {};
BABYLON.SceneOptimizer;
BABYLON.SceneOptimizerOptions;
BABYLON.ShadowsOptimization;
BABYLON.LensFlaresOptimization;
BABYLON.TextureOptimization;
BABYLON.ParticlesOptimization;
BABYLON.PostProcessesOptimization;
BABYLON.RenderTargetsOptimization;
BABYLON.HardwareScalingOptimization;
ns.executeWhenReady;
scene.meshes;
mesh._LODLevels;
mat.ambientTexture;
mat.diffuseColor;
mat.specularColor;
mat.fogEnabled;
mat.emissiveColor;
mat.emissiveTexture;
m.material;
m.material.dispose = function() {};
parentMesh.addLODLevel = function() {};